
project_id = "ronqvzihpffgowyscgfm"
site_url = "https://id-preview--98e56b67-1df6-49a9-99c2-b6a9d4dcdf65.lovable.app"
redirect_urls = ["https://id-preview--98e56b67-1df6-49a9-99c2-b6a9d4dcdf65.lovable.app/auth"]
