
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ronqvzihpffgowyscgfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvbnF2emlocGZmZ293eXNjZ2ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NzM0NzIsImV4cCI6MjA1ODQ0OTQ3Mn0.28ftEjZYpnYOywnRdRbRRg5UKD31VPpuZ00mJH8IQtM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a properly configured client
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    storage: typeof window !== 'undefined' ? window.localStorage : undefined
  }
});

// Helper function to check if a session exists (for debugging)
export const checkSession = async () => {
  const { data, error } = await supabase.auth.getSession();
  console.log("Current session check:", data?.session ? "Session exists" : "No session", error);
  return data?.session;
};

// Debug helper to clear any corrupted auth state
export const clearAuthState = async () => {
  if (typeof window !== 'undefined') {
    // Clear any local storage items that might be causing issues
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key?.includes('supabase') || key?.includes('auth')) {
        console.log("Clearing potentially problematic storage item:", key);
        localStorage.removeItem(key);
      }
    }
  }
  
  // Sign out completely to reset auth state
  const { error } = await supabase.auth.signOut({ scope: 'global' });
  if (error) {
    console.error("Error clearing auth state:", error);
  } else {
    console.log("Auth state successfully cleared");
  }
};

// Function to call our Edge Function to create a demo user and admin user
export const createDemoUser = async () => {
  try {
    console.log("Making request to create-demo-user edge function");
    
    const response = await fetch(`${SUPABASE_URL}/functions/v1/create-demo-user`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${SUPABASE_PUBLISHABLE_KEY}`
      }
    });
    
    if (!response.ok) {
      const errorText = await response.text();
      console.error('Error response from create-demo-user:', response.status, errorText);
      throw new Error(`Failed to create users: ${response.status} ${errorText}`);
    }
    
    const data = await response.json();
    console.log('Create users response:', data);
    
    // If successful, display credentials information
    if (data.success) {
      toast?.({
        title: "Test Accounts Available",
        description: `You can use either the demo credentials (demo@example.com / demo123456) or admin credentials (towenhall@gmail.com / LocaMocha2025!) to log in.`,
      });
    }
    
    return data;
  } catch (error) {
    console.error('Error creating users:', error);
    return { success: false, error };
  }
};

// Add toast import
import { toast } from '@/hooks/use-toast';
